src/alpaca.gresource.xml
src/style-dark.css
src/style.css
src/window.py
src/window.ui

Hope you like it, I have kept the message view sensitive even when a the AI is responding, because it can be useful to write while it's responding.
I have also added clamps for the message bar and chat view.
Plus some minor fixes.

Improved chat view and message bar

---

src/window.ui

I have used an adw toolbarview with an headerbar in the sidebar too.
Don't worry about the missing icons btw.

Sidebar, used AdwToolbarView and added Headerbar

---

README.md
po/pt_BR.po

I'd love if you could double-check if everything is right with the .po file and if any strings have been updated and I didn't notice.

Add Brazilian Portuguese translation

---

po/fr.po

Some French typos were made, I fixed only the ones I noticed in the app.

Fix french typos

---

po/fr.po

Model description translated with deepl and it's very approximate. I quickly reread but that's not high quality translation

French update

---

po/LINGUAS
po/zh_CN.po

Hi,
What I translated:
- UI elements and descriptions
- Models' descriptions
Note translated:
- The changelog

Add Simplified Chinese localization

---

src/meson.build
src/table_widget.py
src/window.py

Closes #131
Basically it searches for a table with regex and then a custom table widget using a column view will parse and display the table, if it fails it will just be a frame with the text inside. It also supports aligning the columns left/center/right.

Added Table widget

---

src/internal.py
src/local_instance.py
src/main.py
src/meson.build
src/window.py

This is to make it able to run outside of flatpak (mainly Nixpkgs, also a cross distro package set), and clear some duplicate code

Better handling of standard paths

---

po/bn.po
po/hi.po

another small fix

---

po/bn.po
po/hi.po
src/window.py

Contains question that can be default randomly. For welcome screen.

some update and fix for welcome screen.

---

po/fr.po

Model description translated with ChatGPT, and it's work really well

Complete french translation

---

po/tr.po

I tried to translate it as best I could.

Added Turkish Translation

---

po/de.po

...a now complete German translation, based on the latest project status.

Full German Translation

---

po/de.po

#267  Translated for the new update

Updated de.po for v2.0.0

---

po/LINGUAS
po/zh_Hans.po

Hi, @Jeffser 
I update the simplified Chinese PO. 
Changing the locale code from zh_CN to zh_Hans, this will allow the translation to be used by a user from another simplified Chinese area (e.g., Singapore).
Also, add @Aleksanaa to the header of the po.
Hi, @Aleksanaa
Please double-check the translations and fix any mistakes. If you need we can discuss it here.
请检查翻译并作出必要修改，如果有任何问题，我们可以在这里讨论。

Update the simplified Chinese translation.

---

po/de.po

Additional German Translation

---

po/te.po

Added te.po - Telugu Translation

---

po/pt_BR.po

These are the translations of some strings.
I plan to translate more strings in the next few days.

Translated somes strings to PT-BR

---

po/cs.po

Translated the important things that are shown in the UI, rest is kept blank expecting to be replaced with english if needs be as it's weird doing translates without context and i don't have the stamina to deal with 3.8K lines of po definitions on my own. @_@
I won't do changes to this merge request and won't maintain it, but might submit more over time.
Main motivation: https://github.com/Arcanyx-org/NiXium/pull/153 expecting my users to annoy me with czech translates.

po/cs: Initial

---

po/it.po

Here are the new strings translated (plus few small improvements on older translations)

Quick update it.po

---

src/main.py

Hello there,
thanks so much for adding me to the list of translators! I've noticed a missing comma to be causing havoc when clicking on the link though, so I quickly patched it and also specified my name instead of GitHub handle, which blends in a bit better with the others.
Hope that's okay! :)
Greetings

Add missing comma causing bug (+ further specify translator)

---

po/ta.po

added translation for tamil language.

added translations for tamil

---

po/LINGUAS
po/ka.po

Hello,
Here's part (most of UI elements should be done) of translation of Alpaca to Georgian.
Ekaterine

i18n: Add Georgian translation

---

src/sql_manager.py
src/window.py

Hello there, hope you're having a lovely day.
I've put some time into adding a few improvements to the `sql_manager.py` file, especially regarding code readability, a bit of function documentation and reducing the amount of code repetitions (as the saying goes, "don't repeat yourself", DRY ;) ) - for this, I've switched to a custom context class that automatically handles opening and closing a DB connection for you.
I also performed some tests and did not find any regressions - _however, as always, I believe some further testing by another party would be reasonable to be extra sure_ - **especially regarding the `generate_numbered_name` function**!
A final pass using `pylint` was done to ensure there's no obvious oversight, and the file should now be much more maintainable. As mentioned in …

Overhaul of sql_manager.py to improve long-term maintainability

---

po/de.po

Hello there,
I've updated the German translations for Alpaca and its new features. As always, I've ran it through `msgfmt` to make sure it's syntactically alright.
Best wishes

Update and improve German translations

---

src/instance_manager.py

This pull request introduces Openrouter.ai API integration. It includes API client integration, configuration for API keys, and implementation to utilize openrouters verious free and paid models.
https://openrouter.ai/
fixing this issue https://github.com/Jeffser/Alpaca/issues/638 https://github.com/Jeffser/Alpaca/issues/635

openrouter ai api support

---

src/instance_manager.py

This MR introduces DeepSeek API integration. It includes API client integration, configuration for API keys, and implementation to utilize DeepSeek models. Solving https://github.com/Jeffser/Alpaca/issues/642 issue.

add deepseek api support

---

src/instance_manager.py

solves https://github.com/Jeffser/Alpaca/issues/651 this

added lambda api support

---

README.md

capitalisation of first word 

---

src/instance_manager.py

patched for support celebras
which is the fastest token generator api provider as per artificial analysis i have tested performance was really good if not the best. I could not hands on their api yet. so I could not have tested the implementation but it should as the documentation is kind of same. https://inference-docs.cerebras.ai/resources/openai .
solves https://github.com/Jeffser/Alpaca/issues/684

support for celebras api

---

src/instance_manager.py

klusterai support

---

po/bn.po

all remaining strings have been updated

Update remaining strings of bn.po

---

po/de.po

Hey there,
I never, _ever_, had this bad of a merge conflict before. Turns out I missed to pull the most recent changes to the `.po` files and edited the old file beforehand, then pulled, then failed to merge. My bad :sob:
`msgmerge` saved my day, and everything should be good now. I'm not seeing any obvious errors.
Have a nice day

Add all missing German translation strings

---

po/te.po

Had a bit of free time so decided to update the translation.

feat(l10n): Updated Telugu (te) Translation

---

src/widgets/speech_recognition.py

STT_MODELS is required to download the whisper model

fix: Added import of STT_MODELS from constants, needed for whisper support

---

src/widgets/instances/openai_instances.py

https://deepinfra.com/docs/openai_api

added deepinfra

---

po/de.po

Hello there!
This pull request adds all the missing German translations for the new features, change logs and settings that have been introduced since the last update of these strings in Alpaca.
Have a great day and best regards! :wave:

Update all German translation strings

---

po/az.po

This commit introduces the full localization for the Azerbaijani (az) language. All strings in the `az.po` file are now translated and ready for integration.

Add Azerbaijani translation

---

po/LINGUAS
po/kab.po

Hi,
I made some kabyle translations for Alpaca.

[i18n] Add kabyle translaton

---

po/kab.po

We added more translations : progress 26.37%
Please credit @ZiriSut under the name MoonShadow, she is doing a great job.

[l10n] Update kab.po translations
