Jeffser/Alpaca

- po/fr.pot
| English	| French	|
|----------|-----------|
| Alpaca	| Alpaga	|
| to chat	| discuter |
| a chat	| une discussion |
Translation harmonized except changelogs (because the original changelogs aren't harmonized)
> French translation 🥖

- src/window.py
Fixes #196, which is a regression from commit 1fbd6a082465387946eea1c7670b5ef84c80c7fd.
> Fix bearer token use for remote ollama APIs.

- po/de.po
No more errors are thrown when starting the “update_translation_files.sh” in relation to the de.po file.
Reason: My previous string formatting was incorrect
FIXED. #265
> Fixed formatting conflicts

- data/com.jeffser.Alpaca.desktop.in
**Is your feature request related to a problem? Please describe.**
Sometimes I've been searching for this app but forgotten the name. Scrolling through gnome's app menu to find it would take a while with the number of things I have installed so it'd be nice to be able to search for it.
**Describe the solution you'd like**
Add some keywords (eg ai, ollama, gpt) to the .desktop file
**Describe alternatives you've considered**
Not adding them 🤷🏻 
I know that the contributing guidelines say to open an issue before contributing to make sure there' no overlapping work but given the size of this change I think you can understand why that's not necessary
> Add keywords to .desktop file

- src/style.css
Hello,
this pull request changes the formatting (more specifically the font family) of the code blocks inside Alpaca chats. It changes it from the standard font to monospace:
This makes it a lot easier to read and often is standard for rendering code.
Hope this helps, even though it's just a small change! :)
> made font family of code blocks monospace

- src/window.py
- src/window.ui
Hello again @Jeffser, here is the pull request without translation files.
I added an option mostly for laptop users to allow omitting the power saver warning at startup because it might get annoying for some people.
For context, many users are regularly using power saver for long periods of time to get longer battery life on mobile devices. This patch gives them the option to not get warned about the very thing they're aware of everytime they use Alpaca:
Hope I could help!
> Add an option to hide the power save warning at startup

- src/custom_widgets/model_widget.py
Instead of relying on a file of available models, prefer the ollama show API to detect vision capabilities.
I need to test this. Every time I run `meson compile`, the resulting executable python script thingy complains about a missing gresource at `/usr/local/share/Alpaca`, and if I shove the file in there, it complains about missing `pypdf`. How do you normally test? Is there a development setup guide?
> Use show API to detect vision.

- po/de.po
Hi!
I've updated `po/de.po` to contain all the missing translations for the German language, including those for all new models and UI elements.
- I have read the [discussion on how to translate](https://github.com/Jeffser/Alpaca/discussions/153)
- None of the strings have been machine-generated or AI-translated
- I've revised all changes to make sure there aren't any obvious spelling mistakes
- The metadata strings at the beginning of the `po/de.po` file have been updated
- I have then invoked `msgfmt -v -C ./po/de.po` to make sure there aren't any syntax errors
Best greetings!
> Add all missing German translation strings

- src/window.py
When generating a title, the <think> tags from reasoning models should be ignored. This change makes that happen.
Previously, titles would include something along the lines of:
```
<think> Hmm, I've been asked to generate a title based on the user's prompt that's under 30 characters
[...]
</think>
*title here*
```
But now it'll just show the `*title here*` bit
> Fix chat names for reasoning models

- SECURITY.md
- src/main.py
Good day,
I've noticed that the current security policy is not very clear about what to do in case of a found vulnerability.
This pull request fixes said issue (#528 can be closed then, too).
Best regards
> Extend security policy to reflect where to disclose vulnerabilities

- src/custom_widgets/message_widget.py
Hello (a third time today!)
I've implemented a patch for the glitchy rendering of some code blocks and the broken table rendering. It seems to be working better now.
BEFORE:
AFTER:
BEFORE:
AFTER:
**I URGENTLY ADVISE YOU TO TEST THIS!** I'm not quite sure I got everything right, and it'd be a pity if I break something. I did not come across any regressions myself, though (4 test cases checked).
This commit should fix issue #526.
This commit does ALSO fixes the table rendering issue #523.
Best wishes!
> Fix bug causing code blocks to be rendered inconsistently

- data/com.jeffser.Alpaca.metainfo.xml.in
Hello there yet again,
this is another minor fix addressing a dead link on the application's Flathub page:
The "Contributing" URL points to this outdated page:
This pull request changes said link to point directly to the new `CONTRIBUTING.md` file at the project's root directory, avoiding sending users to an outdated page and saving them an extra click.
Best wishes
> Update contribution link for Flathub appearance

- src/window.py
Hi,
this pull request fixes Alpaca starting to count pages of imported documents from zero, which is rather counter-intuitive for humans that ask stuff like "What's on page 1?". It simply adds 1 to the page index.
How it looks when this fix is applied:
Addresses issue #543.
Greets
> Use human-like counting starting from 1 instead of 0 for imported document pages

- .gitignore
- src/constants.py
- src/generic_actions.py
- src/instance_manager.py
- src/internal.py
- src/main.py
- src/meson.build
- src/window.py
Hello and good day,
I refactored a small amount of repeating code and constants and encapsulated these values in their new, own `constants.py` file - a file where everything that's related to non-changing values can be placed, so if something changes in the future, there's one central place to consult and edit!
For example, you do now have this handy `Platforms` class that keeps track of the `sys.platform` values of the platforms that aren't yet fully supported. Once every single feature works on macOS for example, you can simply remove it from the `ported` tuple and it'll be reflected in all of Alpaca.
Translators are also no longer in the `main.py` file but rather in the `constants.py` file, where they are in a more encapsulated space.
I also added a `.gitignore` file that allows other …
> Minor refactoring and encapsulation of constants, add .gitignore

- src/custom_widgets/chat_widget.py
Hello there yet again,
as mentioned in issue #586, a KeyError is raised when using vision models with the latest version of Alpaca. This patch introduces a quick and temporary fix for this until your college workload decreases.
Kind regards
> Patch key error when using vision models (temporary hotfix)

- src/custom_widgets/message_widget.py
Good day,
I've seen the issue on OpenThinker models giving a different output from what reasoning models normally do (#604) and wrote a patch for it, which is included in this pull request.
I did not stumble upon any regressions due to this patch, however I noticed that the "Thought" badge would go away after editing a message, adding a Thought to it by manually typing out `<think>` and `</think>` (or OpenThinker's version of that, respectively) and then switching to another chat and back to the chat where the edit was made. This is an incredibly low priority bug, so I wouldn't bother creating an issue for it.
Greetings!
> Fix wrong rendering of OpenThinker reasoning output

- src/window.py
Hello, hope you're having a lovely day.
I've added a small function to automatically select the correct default model for a given instance, so that the right one is immediately selected upon app startup or after switching instances - not just after creating a new chat.
This will fix #695.
This fix does not address the potential issue of Alpaca no longer being able to remember which model was last selected in what chat, however that occurs both with the patch and without it.
Hope that helps, and Cheers! :smile:
> Automatically select correct default model every time

- src/custom_widgets/chat_widget.py
- src/custom_widgets/dialog_widget.py
- src/custom_widgets/model_manager_widget.py
Hi,
this pull request now makes Alpaca catch the exception thrown by Gtk.FileDialog when cancelling the action, as it's never a good thing to have exceptions raised in production when something intended happens.
The exception will just silently error out; this is fine, as there is no reason to log it because it is perfectly expected behavior. This could've wreaked havoc if any important control flow would've followed after the dialog selection.
**Also, this pull request fixes a bug that would prevent the user from opening the model profile picture options dialog. I just passed `self` as parent to the Options object, but am unsure about whether this is correct. Please correct it if I'm wrong :smile:**
Have a good day
> Handle dismission of file picker gracefully

- src/available_models.json
- src/custom_widgets/model_manager_widget.py
Hi there,
I've added a tag to filter by models with reasoning capabilities due to request in #734.
Each model with reasoning now holds a tag called "Reasoning" that can also be used to filter by those that support thinking processes.
This pull request will close #734.
Best regards!
> Add reasoning tag to models to allow for better filtering

- src/available_models.json
Hey there,
I know you have your internal tooling to deal with the `available_models.json` file right now, however, I've noticed that the `vision` tag is heavily duplicated all over the. This could be fixed in your script by using a `set`, effectively de-duplicating such tags.
You could consider open-sourcing the internal tooling into a folder like `scripts/` to make these errors fixable for everyone.
Best regards
> Remove duplicated "vision" tags

- src/available_models.json
Hi,
this pull request updates `available_models.json` to include the new "reasoning" tag for other newly added models that haven't received the tag yet.
Greets
> Add missing reasoning tags to new models

- src/widgets/chat.py
`image` is a dictionary, not an object. so it doesn't implement .get_content()
This fixes a crash that I've experienced with Vision models, where it would never respond when you attach images.
Without the patch:
With the patch (still doesn't know the character, but that's fine):
> Replace image.get_content() with image["content"]

- src/widgets/blocks/code.py
Hello there,
this pull request fixes issue https://github.com/Jeffser/Alpaca/issues/858 by simply adding a fallback for the `javascript` language descriptor in markdown syntax.
Greets
> Add JavaScript fallback for code blocks

- src/constants.py
- src/widgets/instances/ollama_instances.py
- src/widgets/instances/openai_instances.py
Hi Jeffry,
I know the title generation issues have already been addressed by you for a few times, but I've seen issue #773 and wanted to add some final fixes.
A limit of 50 tokens for generation is quite generous, as that would equal a maximum title length of up to 37,5 words of pure text - just for a title! On the other hand, tokens for special characters are used up way faster, so the number of tokens to generate should never be lower than the maximum title length in characters.
This commit adds title length clamping to 30 characters with dots (...) added if text gets too long. The maximum tokens generated are 31 (30 for the title + 1 for the emoji).
It also features some minor re-factoring for better maintainability of the prompts and amount of tokens into `constants.py`.
Hope you're …
> Minor improvements for title generation

- src/window.py
Addressing an issue where messages containing only whitespace (like spaces or newlines) were being sent. The raw message is now stripped of leading and trailing whitespace before validation. This ensures that only messages with actual content go through.
Example:
This empty string being sent seem to also break the chat. Since AI response now just keep loading forever.
> Prevent sending empty messages

- src/gtk/help-overlay.ui
- src/widgets/preferences.py
- src/window.py
Align zoom logic between Preferences and keyboard shortcuts, ensuring consistent scaling.
- Refactored both the Preferences dialog (`zoom_changed`) and window shortcut zoom logic to use a shared DPI calculation based on a 96*1024 baseline. [GTK Standard](https://docs.gtk.org/gtk4/property.Settings.gtk-xft-dpi.html)
- Zoom is now consistently clamped between 100 and 200 in steps of 10, matching the UI spinbox.
- Removed cumulative DPI calculations to prevent drift and ensure both settings and shortcuts always result in identical UI scaling.
- Both zoom methods now update and apply the same GSettings value for persistence and UI sync.
- This ensures users experience consistent zoom behavior regardless of whether they use shortcuts or the Preferences dialog.
I've cooked this up :) : …
> Add Zoom In/Out shortcuts and ensure Consistent Scaling
